name: Bun CI

on:
  workflow_call:
    inputs:
      bun-version:
        description: 'Bun version'
        required: false
        default: 'latest'
        type: string
      working-directory:
        description: 'Directory to run commands in'
        required: false
        default: '.'
        type: string
      run-test:
        description: 'Run bun test'
        required: false
        default: true
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2
        with:
          bun-version: ${{ inputs.bun-version }}
      - run: bun install --frozen-lockfile
        working-directory: ${{ inputs.working-directory }}
      - if: ${{ inputs.run-test }}
        run: bun test
        working-directory: ${{ inputs.working-directory }}
