name: Go CI

on:
  workflow_call:
    inputs:
      go-version-file:
        description: 'Path to go.mod'
        required: false
        default: 'go.mod'
        type: string
      working-directory:
        description: 'Directory to run commands in'
        required: false
        default: '.'
        type: string
      run-race:
        description: 'Run tests with -race'
        required: false
        default: false
        type: boolean
      run-vet:
        description: 'Run go vet'
        required: false
        default: true
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ inputs.go-version-file }}
          cache: true

      - name: Test
        run: |
          cd ${{ inputs.working-directory }}
          go test ./...

      - name: Test with race detector
        if: ${{ inputs.run-race }}
        run: |
          cd ${{ inputs.working-directory }}
          go test -race ./...

      - name: Vet
        if: ${{ inputs.run-vet }}
        run: |
          cd ${{ inputs.working-directory }}
          go vet ./...
